//
// Autogenerated by Thrift
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var TimeServer = {}
TimeServer.Thrift = {}
TimeServer.Thrift.TimeInfoStruct = function(args){
this.Time = ''
if( args != null ){if (null != args.Time)
this.Time = args.Time
}}
TimeServer.Thrift.TimeInfoStruct.prototype = {}
TimeServer.Thrift.TimeInfoStruct.prototype.read = function(input){ 
var ret = input.readStructBegin()
while (1) 
{
  var ret = input.readFieldBegin()
  var fname = ret.fname
  var ftype = ret.ftype
  var fid   = ret.fid
  if (ftype == Thrift.Type.STOP) 
    break
  switch(fid)
  {
    case 1:    if (ftype == Thrift.Type.STRING) {
      var rtmp = input.readString()
this.Time = rtmp.value
    } else {
      input.skip(ftype)
    }
    break
    default:
      input.skip(ftype)
  }
  input.readFieldEnd()
}
input.readStructEnd()
return
}

TimeServer.Thrift.TimeInfoStruct.prototype.write = function(output){ 
output.writeStructBegin('TimeInfoStruct')
if (null != this.Time) {
  output.writeFieldBegin('Time', Thrift.Type.STRING, 1)
  output.writeString(this.Time)
  output.writeFieldEnd()
}
output.writeFieldStop()
output.writeStructEnd()
return
}

